some modification

diff --git a/.github/workflows/cdk-destroy.yml b/.github/workflows/cdk-destroy.yml
--- a/.github/workflows/cdk-destroy.yml
+++ b/.github/workflows/cdk-destroy.yml
@@ -8,6 +8,20 @@ permissions:
   contents: read
 
 jobs:
+    authorize:
+        name: authorize workflow access
+        runs-on: ubuntu-latest
+        environment: production
+        steps:
+            - name: Authorization Check
+              run: |
+                AUTHORIZED_USERS="Ali-Hammoud-12"
+                GITHUB_ACTOR="${{ github.actor }}"
+
+                if [[ ! " $AUTHORIZED_USERS " =~ " $GITHUB_ACTOR " ]]; then
+                  echo "❌ Unauthorized user. Deployment aborted."
+                  exit 1
+                fi
     destroy:
         name: Destroy CDK Stack
         environment: production
